# Generated by Django 3.0.5 on 2020-06-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profilebuku', '0004_auto_20200611_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='image_profile',
            field=models.ImageField(blank=True, upload_to='image_profile/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='slug',
            field=models.SlugField(),
        ),
    ]
