# Generated by Django 3.0.5 on 2020-05-03 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('deskripsi', models.TextField()),
                ('image_categories', models.ImageField(upload_to='categories/')),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('deskripsi', models.TextField()),
                ('image_sub_categories', models.ImageField(upload_to='categories/')),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Cerita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('chapter', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Draft', 'draft'), ('Ready', 'ready')], max_length=80)),
                ('slug', models.SlugField()),
                ('isi_cerita', models.TextField()),
                ('image_cover', models.ImageField(upload_to='cerita/%Y/%m/%d')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story.Categories')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='categories',
            name='sub_categories',
            field=models.ManyToManyField(to='story.SubCategories'),
        ),
    ]
