# Generated by Django 3.0.5 on 2020-05-03 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cerita',
            name='categories',
        ),
        migrations.AddField(
            model_name='cerita',
            name='categories',
            field=models.ManyToManyField(to='story.Categories'),
        ),
    ]
