# Generated by Django 3.0.5 on 2020-05-03 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_auto_20200503_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='sub_categories',
        ),
        migrations.AddField(
            model_name='cerita',
            name='sub_categories',
            field=models.ManyToManyField(to='story.SubCategories'),
        ),
    ]
